spring:
  security:
    user:
      name: admin
      password: pwd
    oauth2:
      client:
        registration:
          google:
            client-id: xxx
            client-secret: xxx
            scope:
              - openid
              - profile
              - email