server:
  port: 8080

spring:
  application:
    name: section11

  datasource:
    url: jdbc:mysql://localhost:3306/security_udemy_course_section11
    username: user
    password: pwd
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.springframework.security: INFO
  pattern:
    console: '%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n'

jwt:
  secret: d185808d574baad85deb4d5c17094862cb414f6fc5d3a2b426387e3d4713d004