server:
  port: 8080

spring:
  application:
    name: section13

  datasource:
    url: jdbc:mysql://localhost:3306/security_udemy_course_section13
    username: user
    password: pwd
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/security_udemy_course_section13

logging:
  level:
    org.springframework.security: INFO
  pattern:
    console: '%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n'

